#!/bin/bash

#compile parsers
#cd parser/formula
#node ../../../jison/ports/php/php.js formula.jison
#cd ../../

# directories of the JS files
JS_IN_DIR='./Sheet'
JS_OUT_DIR='.'

#these are the paths to the final combined files that you want to have in the end

JS_TEMP=""
JS_WRAPPER=$(<"$JS_IN_DIR/wrapper.js")
JS_COMBINED_FILE="$JS_OUT_DIR/jquery.sheet.js"
JS_COMBINED_FILE_MIN="$JS_OUT_DIR/jquery.sheet.min.js"

JS_FILES=(
	#namespace first
		Base.js

	#non-constructors next
    	fn.js
    	sheet.js
    	thread.js
    	utilities.js

	#children namespaces next
		Loader/HTML.js
		Loader/JSON.js
		Loader/XML.js

	#constructors next
		ActionUI.js
		Cell.js
		CellHandler.js
		CellTypeHandlers.js
		CellRange.js
		Highlighter.js
		SpreadsheetUI.js
		Theme.js

	#environment correction last
		environmentCorrection.js
)

PARSER_FILES=(
	parser/formula/formula.js
	parser/tsv/tsv.js
)


#clear the files
> $JS_COMBINED_FILE
> $JS_COMBINED_FILE_MIN

#run thru the JS files
for F in ${JS_FILES[@]}; do
  CONTENTS=$(<"$JS_IN_DIR/$F")
  JS_TEMP+="$CONTENTS"
done

echo "${JS_WRAPPER//CODE_HERE/"$JS_TEMP"}" > $JS_COMBINED_FILE

#run thru the parser files
for F in ${PARSER_FILES[@]}; do
  CONTENTS=$(<"$F")
  echo "$CONTENTS" >> $JS_COMBINED_FILE
done

#compress it
yui-compressor -o $JS_COMBINED_FILE_MIN $JS_COMBINED_FILE

#add the file to the git base
git add $JS_COMBINED_FILE
git add $JS_COMBINED_FILE_MIN